# Generated by Django 3.2.7 on 2021-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('spider', models.IntegerField()),
            ],
            options={
                'db_table': 'COMMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('sex', models.TextField()),
                ('face', models.TextField()),
                ('sign', models.TextField()),
                ('level', models.IntegerField()),
                ('attention', models.IntegerField()),
                ('fans', models.IntegerField()),
                ('localpic', models.IntegerField()),
                ('spider', models.IntegerField()),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('bvid', models.TextField()),
                ('cid', models.IntegerField()),
                ('pic', models.TextField()),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('keywords', models.TextField()),
                ('copyright', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('videos', models.IntegerField()),
                ('pubdate', models.IntegerField()),
                ('view', models.IntegerField()),
                ('danmaku', models.IntegerField()),
                ('like', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('favorite', models.IntegerField()),
                ('share', models.IntegerField()),
                ('reply', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('localpic', models.IntegerField()),
                ('spider', models.IntegerField()),
            ],
            options={
                'db_table': 'VIDEO',
                'managed': False,
            },
        ),
    ]
