# Generated by Django 3.2.7 on 2021-09-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'managed': False, 'ordering': ['-view']},
        ),
    ]
