# Generated by Django 3.2.7 on 2021-09-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_alter_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True, 'ordering': ['-view']},
        ),
    ]
