# Generated by Django 3.2.7 on 2021-09-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_alter_video_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-view'], name='view_idx'),
        ),
    ]
