# Generated by Django 3.2.7 on 2021-09-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_video_view_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
