# Generated by Django 3.2.7 on 2021-09-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_auto_20210908_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'ordering': ['-fans']},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-fans'], name='fans_idx'),
        ),
    ]
