# Generated by Django 3.2.7 on 2021-09-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0006_auto_20210908_1812'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['owner'], name='owner_idx'),
        ),
    ]
